version: '3.7'

services:
  app:
    build: ./backend/.
    ports:
      - 3333:3333
    env_file:
      - ./backend/.env
    depends_on:
      - db
    environment:
      - DATABASE_URL=$DATABASE_URL

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_DB